package de.maengelmelder.mainmodule.utils

import android.annotation.SuppressLint
import android.app.Activity
import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.content.res.Resources
import android.graphics.*
import android.graphics.drawable.BitmapDrawable
import android.graphics.drawable.Drawable
import android.graphics.drawable.LayerDrawable
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.text.Html
import android.text.Spanned
import androidx.core.content.ContextCompat
import android.util.DisplayMetrics
import android.util.Log
import android.util.TypedValue
import androidx.annotation.NonNull
import androidx.preference.PreferenceManager
import com.google.android.gms.maps.model.LatLng
import de.maengelmelder.mainmodule.BuildConfig
import de.maengelmelder.mainmodule.MMConstants
import de.maengelmelder.mainmodule.R
import de.maengelmelder.mainmodule.activities.TermsActivity
import de.maengelmelder.mainmodule.objects.BrowsableQueryParam
import de.maengelmelder.mainmodule.objects.LayerswitcherInfo
import de.maengelmelder.mainmodule.objects.MapLayerInfo
import de.maengelmelder.mainmodule.objects.MessageGroup
import kotlinx.coroutines.coroutineScope
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileNotFoundException
import java.io.IOException
import java.net.URLDecoder
import java.nio.charset.StandardCharsets
import java.util.regex.Pattern
import kotlin.jvm.Throws

/**
 *
 * ## Overview
 * This object is used as the proxy to retrieve resources in drawable folders. It also handles default values and exceptions
 */
internal object ResourceProxy {

    /**
     * @property mMarkerMap the hashmap used to cache the loaded [Drawable] with its identifier
     * @property mPhoneId Used to store the unique device id generated by [DeviceUuidFactory]
     */

    private val mMarkerMap: HashMap<String, Drawable> = HashMap()
    private var mPhoneId: String? = null

    /**
     * Get the [Drawable] marker identified by its name and color. The drawable will also be cached temporarily using its name and color.
     * The method uses the base marker R.drawable.mm_marker and modifies it based on the given id and color. The base marker has the id
     * "frame" to indicate the marker's frame color and "icon" to indicate marker's icon. If the marker exists beforehand,
     * it will be returned instead of recreating it
     *
     * @param context Context
     * @param color the color of the marker. Allowed are red, blue, green, green2, yellow, white, grey
     * @param id the marker's Id. Check the drawable folder for available Ids
     * @param selected if true, it will replace the frame of the marker to the selected one (green_sel, red_sel, etc.)
     *
     * @see LayerDrawable.setDrawableByLayerId
     *
     * @return the Drawable marker with corresponding color and id.
     */
    fun getMarker(context: Context, color: String, id: String, selected: Boolean = false): Drawable {
        // Sets the marker's name for identification
        var name = "marker_${id}_${color}"
        if (selected) name += "_sel"

        // Find it on the map first for existing marker
        var marker = mMarkerMap[name]
        val frameSuffix = MMConstants.SpecializedMarkerFrameSuffix

        if (marker == null) {
            // Get the correct resource id for frame and icon
            val colorString = if (frameSuffix.isNotEmpty()) "${color}_${frameSuffix}" else color
            val frameName = if (!selected) colorString else "${colorString}_sel"
            val baseMarker = ContextCompat.getDrawable(context, R.drawable.mm_marker) as LayerDrawable
            var iconResId = doGetResourceId(context, "symbol_$id", "drawable")
            var frameResId = doGetResourceId(context, frameName, "drawable")

            // Revert marker icon to symbol_0 if it does not exist
            if (iconResId == 0) {
                iconResId = R.drawable.symbol_0
            }

            // Revert to normal frame color if it does not exist
            if (frameResId == 0) {
                frameResId = doGetResourceId(context, color, "drawable")
            }

            val iconRes = ContextCompat.getDrawable(context, iconResId)
            var frameRes = try {
                ContextCompat.getDrawable(context, frameResId)
            } catch (e: Exception) {
                // Exception may happen when the given color from server is not found inside the App
                // Therefore we use "white" color as default
                null
            }
            if (frameRes == null) {
                frameRes = ContextCompat.getDrawable(context, doGetResourceId(context, "white", "drawable"))
            }

            // Replace the base marker's icon and frame to the picked ones
            baseMarker.setDrawableByLayerId(R.id.frame, frameRes)
            baseMarker.setDrawableByLayerId(R.id.icon, iconRes)

            // For markers with ID above 199 or 18, they don't have bottom padding to compensate the marker's pointy part
            // Instead, we add it ourselves, so the icon is correctly positioned inside the marker
            val idInt = try { id.toInt() } catch (e: NumberFormatException) { -1 }
            // Per T17958, MING icons already have bottom margin so we don't need to add it programmatically
            if ((idInt in 200..999) || idInt == 18) {
                try {
                    val bottom = 9 * context.resources.displayMetrics.density
                    baseMarker.setLayerInset(1, 0, 0, 0, bottom.toInt())
                } catch (e: Exception) { }
            }

            // Create a bitmap drawable from the given marker, since the map can only accept bitmaps
            marker = layerToBitmapDrawable(res = context.resources, dlayer = baseMarker)
            mMarkerMap[name] = marker
        }

        return marker
    }

    /**
     * Returns a group marker as Bitmap for closely-densed messages inside the [MessageGroup] parameter.
     *
     * @param ctx Context
     * @param group [MessageGroup] object
     */
    fun getGroupMarker(ctx: Context, group: MessageGroup, onDone: (Drawable) -> Unit) {
        var timeToGen = 0L
        if (BuildConfig.debug) {
            timeToGen = System.currentTimeMillis()
        }
        if (group.messages.isEmpty()) return

        if (group.messages.size == 1) {
            val msg = group.messages[0]
            if (MMConstants.UseMarkerUri) {
                MapMarkerFromURLCoroutine.run(msg.markerUrl) {
                    onDone(BitmapDrawable(ctx.resources, it))
                }
            } else {
                onDone(getMarker(ctx, msg.colorString, msg.id, false))
            }
        } else {
            // Get the bitmaps of the first 2 (or 3) messages
            val maxNum = group.groupMemberDisplayCount
            if (MMConstants.UseMarkerUri) {
                val urls = group.messages.map { m -> m.markerUrl }
                MapMarkerFromURLCoroutine.runMultiple(urls) {
                    val finalBitmap = combineBitmapsForMarker(it.filterNotNull(), maxNum)
                    onDone(BitmapDrawable(ctx.resources, finalBitmap))
                }
            } else {
                val bitmaps = arrayListOf<Bitmap>()
                for (i in 0 until maxNum) {
                    val msg = group.messages[i]
                    bitmaps.add((getMarker(ctx, msg.colorString, msg.category.markerId, false) as BitmapDrawable).bitmap)
                }
                val finalBitmap = combineBitmapsForMarker(bitmaps, maxNum)
                onDone(BitmapDrawable(ctx.resources, finalBitmap))
            }
        }
        /*
        // Prepare offset and dimensions for the grouped markers
        val xOffset = bitmaps[1].width / 4f
        val yOffset = xOffset / 2f
        val bitWidth = bitmaps[1].width + (if (maxNum == 3) xOffset * 2 else xOffset)
        val bitmapToUse = if (maxNum == 3) bitmaps[2] else bitmaps[1]
        val bitHeight = bitmapToUse.height + yOffset

        // Containers for the group marker
        val finalBitmap = Bitmap.createBitmap(bitWidth.toInt(), bitHeight.toInt(), Bitmap.Config.ARGB_8888)
        val canvas = Canvas(finalBitmap)

        // Set the left position (1st marker)
        canvas.drawBitmap(bitmaps[0], 0f, 0f, null)
        // Set right position for 3+ messages in a group
        if (maxNum == 3) {
            canvas.drawBitmap(bitmaps[1], 2f * xOffset, 0f, null)
        }
        // Set the lower middle position
        canvas.drawBitmap(bitmapToUse, xOffset, yOffset, null)

        if (BuildConfig.debug) {
            Log.d("GroupMarkerGeneration",
                    "Time to generate for $maxNum markers: " + (System.currentTimeMillis() - timeToGen) + " ms")
        }

        // Returns the bitmapdrawable of the group marker
        return BitmapDrawable(ctx.resources, finalBitmap)
        */
    }

    /**
     * Combine the list of marker bitmaps into one.
     * To see the example, zoom out the map until you see a group of 3 markers on top of each other
     *
     * @param bitmaps list of [Bitmap] marker images
     * @param displayCount number of marker bitmaps that should be shown on map. Usually 3
     * @return the combined bitmap marker image
     */
    private fun combineBitmapsForMarker(bitmaps: List<Bitmap>, displayCount: Int): Bitmap {
        // Prepare offset and dimensions for the grouped markers
        val xOffset = bitmaps[1].width / 4f
        val yOffset = xOffset / 2f
        val bitWidth = bitmaps[1].width + (if (displayCount == 3) xOffset * 2 else xOffset)
        val bitmapToUse = if (displayCount == 3) bitmaps[2] else bitmaps[1]
        val bitHeight = bitmapToUse.height + yOffset

        // Containers for the group marker
        val finalBitmap = Bitmap.createBitmap(bitWidth.toInt(), bitHeight.toInt(), Bitmap.Config.ARGB_8888)
        val canvas = Canvas(finalBitmap)

        // Set the left position (1st marker)
        canvas.drawBitmap(bitmaps[0], 0f, 0f, null)
        // Set right position for 3+ messages in a group
        if (displayCount == 3) {
            canvas.drawBitmap(bitmaps[1], 2f * xOffset, 0f, null)
        }
        // Set the lower middle position
        canvas.drawBitmap(bitmapToUse, xOffset, yOffset, null)
        return finalBitmap
    }

    /**
     * Call to [Resources.getIdentifier]
     */
    @SuppressLint("DiscouragedApi")
    private fun doGetResourceId(ctx: Context, name: String, defType: String) : Int {
        return ctx.resources.getIdentifier(name, defType, ctx.packageName)
    }

    /**
     * Converts [LayerDrawable] to [BitmapDrawable]. Since some Map engine only accepts [BitmapDrawable] and the markers themselves are
     * structured on top of each other (marker background and icon), this method can easily transform it
     *
     * @param res [Resources]
     * @param dlayer the [LayerDrawable] of the loaded marker
     * @return [BitmapDrawable] that contains the marker image
     *
     * @see getMarker
     */
    private fun layerToBitmapDrawable(res: Resources, dlayer: LayerDrawable): BitmapDrawable {
        val bitmap = Bitmap.createBitmap(dlayer.intrinsicWidth, dlayer.intrinsicHeight, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)
        dlayer.setBounds(0, 0, dlayer.intrinsicWidth, dlayer.intrinsicHeight)
        dlayer.draw(canvas)

        val bmpD = BitmapDrawable(res, bitmap)
        bmpD.setBounds(0, 0, dlayer.intrinsicWidth, dlayer.intrinsicHeight)
        return bmpD
    }

    /**
     * Get the photo file path. Required in Android 7.0+ since the photo-saving functionality from camera changed a bit
     *
     * @param c Context
     * @param fileName the name of the file without extension
     * @param ext Extension without dot (.)
     *
     * @return The file containing the photo
     */
    fun getPhotoFilePath(c: Context, fileName: String, ext: String): File {
        val path = File(c.filesDir, "images")
        // If u don't create the folder first, the camera intent will return without any error (and ofc, no images) !!!
        if (!path.exists()) path.mkdir()
        return File(path, "$fileName.$ext")
    }

    /**
     * Caller to [doSaveImageToMediaStore] with [File] as param
     * @param context Context object
     * @param imageFile valid Image file
     */
    @Throws(IOException::class, IllegalArgumentException::class, FileNotFoundException::class)
    fun saveImageToMediaStore(context: Context, imageFile: File) {
        try {
            val imageBitmap = BitmapFactory.decodeFile(imageFile.absolutePath)
            saveImageToMediaStore(context, imageFile.name, imageBitmap)
        } catch (e: IOException) {
            throw e
        } catch (e: IllegalArgumentException) {
            throw e
        } catch (e: FileNotFoundException) {
            throw e
        }
    }

    /**
     * Beginning from Android 10+, images from app-specific folders are no longer scanned by gallery apps.
     * Therefore, images taken from camera must then be saved through MediaStore API so it is available in gallery apps
     *
     * @param context Context object
     * @param filename name of the file shown in gallery (<filename>.<ext>)
     * @param imageBitmap [Bitmap] object
     */
    @Throws(IOException::class, FileNotFoundException::class)
    fun saveImageToMediaStore(context: Context, filename: String, imageBitmap: Bitmap): Uri? {
        val contentResolver = context.contentResolver
        var transferUri: Uri? = null
        if (contentResolver != null) {
            // build content values
            val contentValues = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, filename)
                put(MediaStore.MediaColumns.MIME_TYPE, "image/jpg")
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_PICTURES)
            }

            try {
                // Insert with mediastore API
                transferUri = contentResolver.insert(
                    MediaStore.Images.Media.EXTERNAL_CONTENT_URI,
                    contentValues
                )?: throw IOException("Failed to create transfer uri for app-specific image")

                // save the insertion Uri
                contentResolver.openOutputStream(transferUri)?.use {
                    if (!imageBitmap.compress(Bitmap.CompressFormat.JPEG, 100, it)) {
                        throw IOException("Failed to save bitmap to mediastore")
                    }
                }
            } catch (e: IOException) {
                transferUri?.let { u -> contentResolver.delete(transferUri, null, null) }
                throw e
            } catch (e: FileNotFoundException) {
                throw e
            }
        }

        return transferUri
    }

    /**
     * Wrapped call to [DeviceUuidFactory.getDeviceUuid]. It caches the device UUID before generating a new one
     *
     * @param c Context
     * @return the device's UUID
     *
     * @see DeviceUuidFactory.getDeviceUuid
     */
    fun getPhoneId(c: Context): String {
        if (mPhoneId == null) mPhoneId = DeviceUuidFactory(c).deviceUuid.toString()
        return mPhoneId!!
    }

    /**
     * Transform DP to pixel
     */
    fun dpToPixel(res: Resources, dp: Float): Float {
        return TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, dp, res.displayMetrics)
    }

    /**
     * Get default error messages pertaining to HTTP error codes.
     *
     * @param ctx Context
     * @param errCode HTTP Error codes
     *
     * @return localized, print-ready error message
     */
    fun getLocalizedHttpErrorMessage(ctx: Context, errCode: Int): String = when (errCode) {
        400 -> ctx.getString(R.string.def_err_400)
        401 -> ctx.getString(R.string.def_err_401)
        403 -> ctx.getString(R.string.def_err_403)
        404 -> ctx.getString(R.string.def_err_404)
        408 -> ctx.getString(R.string.def_err_408)
        500 -> ctx.getString(R.string.def_err_500)
        503 -> ctx.getString(R.string.def_err_503)
        else -> ""
    }

    /**
     * SDK-compatible call to [Html.fromHtml]
     */
    fun fromHTML(htmlString: String): Spanned {
        return if (Build.VERSION.SDK_INT >= 24) {
            Html.fromHtml(htmlString, Html.FROM_HTML_MODE_LEGACY)
        } else {
            Html.fromHtml(htmlString)
        }
    }

    /**
     * Check whether a file exists in Assets folder.
     * @param c [Context] object
     * @param path path to the file in assets folder (After the "assets" path)
     */
    fun fileExistsInAssets(c: Context, path: String): Boolean {
        val am = c.resources.assets
        val inpStream = try { am.open(path) } catch (e: IOException) { null }
        val exists = inpStream != null
        inpStream?.close()
        return exists
    }

    /**
     * Check if user has accepted both terms and policy
     */
    fun hasUserAcceptedTermsAndCondition(c: Context): Boolean {
        val pref = PreferenceManager.getDefaultSharedPreferences(c)
        return pref.getBoolean(TermsActivity.PREF_TERMS_ACCEPTED, false)
                && pref.getBoolean(TermsActivity.PREF_POLICY_ACCEPTED, false)
    }

    /**
     * Reads a file from assets folder and return the content as string
     */
    fun readFromAssets(c: Context, filePath: String): String {
        return c.assets.open(filePath).bufferedReader().use { it.readText() }
    }

    /**
     * Reads serialized object from intent.
     * Starting from Android SDK 33, [Intent.getSerializableExtra] is deprecated
     */
    @Suppress("DEPRECATION")
    fun<T: java.io.Serializable> getSerializeableExtra(i: Intent, key: String, clazz: Class<T>): T? {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            return i.getSerializableExtra(key, clazz)
        }
        return i.getSerializableExtra(key) as? T
    }

    /**
     * Transform URL into <a>-Tag URLs, effectively becoming HTML text
     */
    fun linkifyText(text: String): String {
        val regex = Regex("""\b((?:https://|www\.)[^\s<]+)""", RegexOption.IGNORE_CASE)
        val linkedText = regex.replace(text) { matchResult ->
            val url = matchResult.value.let {
                if (it.startsWith("www.", ignoreCase = true)) "https://$it" else it
            }
            """<a href="$url">${matchResult.value}</a>"""
        }
        val htmlText = linkedText.replace("\n", "<br/>")
        return htmlText
    }

    /**
     * Retrieves additional map layers
     */
    fun getAdditionalMapLayerInfo(c: Context): Pair<LayerswitcherInfo?, List<MapLayerInfo>>? {
        val info = readFromAssets(c, "mm-geojson/settings.json")
        val infoJSON = try { JSONObject(info) } catch (e: Exception) { null }
        if (infoJSON == null) return null

        val mapLayers = arrayListOf<MapLayerInfo>()

        infoJSON.optJSONArray("layers")?.let {
            (0..<it.length()).forEach { idx ->
                val newLayer = MapLayerInfo.fromJSON(it.getJSONObject(idx))
                mapLayers.add(newLayer)
            }
        }

        var layerInfo: LayerswitcherInfo? = null
        infoJSON.optJSONObject("info")?.let { s ->
            layerInfo = LayerswitcherInfo(
                singleSwitch = s.optBoolean("single_switch", false),
                switchName = s.optString("switch_name")
            )
        }

        return Pair(layerInfo, mapLayers)
    }

    /**
     *  parse queryparameter (e.g. a=1&b=2&c=3) into map of String as key and Any? as value
     *  @param queryParameter query parameters in string
     *  @return returns map of key-value
     */
    fun parseQueryParameter(queryParameter: String): Map<String, Any?> {
        // Log.d("ParseQueryParameter", queryParameter)

        val params = queryParameter.split("&")
        val hash: HashMap<String, Any?> = hashMapOf()
        hash["attribute_values"] = hashMapOf<String, Any?>()

        val attributePattern = Regex("^(selected|force)_attribute(\\d+)$")
        params.forEach { p ->
            val keyVal = p.split("=")
            if (keyVal.size >= 2) {
                // Special case for attribute
                val attrPatternResult = attributePattern.find(keyVal[0])
                val decodedValue = URLDecoder.decode(keyVal[1])
                if (attrPatternResult != null && attrPatternResult.groupValues.size > 1) {
                    val type = attrPatternResult.groupValues[1]
                    val attrId = attrPatternResult.groupValues[2]
                    (hash["attribute_values"] as HashMap<String, Any?>).let { m ->
                        if (type == "force" // Forced
                            // Not forced and the value is not filled yet (we prioritize forced over selected)
                            || (type == "selected" && !m.containsKey(attrId + "_force"))
                            ) {
                            m[attrId] = decodedValue
                            m[attrId + "_force"] = type == "force"
                        }
                    }
                } else {
                    hash[keyVal[0]] = decodedValue
                }
            }
        }
        return hash
    }

    /**
     * Validate the given query parameter (e.g. a=1&b=2&c=3) whether it can be used as parameter for new bms message
     * Used in deeplinking activity for validating the URL
     *
     * @param c Context
     * @param query Query parameter in string
     * @param onDone function to be called after the validation is done
     */
    fun validateBrowsableUrlQuery(c: Context, query: String, onDone: (Boolean, BrowsableQueryParam?, String) -> Unit) {
        val param = parseQueryParameter(query)
        val forceLoc = try { (param["force_loc"] as String).toInt() == 1 } catch (e: Exception) { false }
        val locationAvailable = param.contains("lat") && param.contains("lon")
        val lat = try { (param["lat"] as String).toDouble() } catch (e: Exception) { 0.0 }
        val lon = try { (param["lon"] as String).toDouble() } catch (e: Exception) { 0.0 }
        val forceTypeid = try { (param["force_typeid"] as String).toLong() } catch (e: Exception) { 0 }
        val typeid = try { (param["selected_typeid"] as String).toLong() } catch (e: Exception) { 0 }

        /**
         * TODO: implement `filter_typeid=2,3,4,5,6` to filter the list of viewable categories, just like frontend wizard.
         */

        // Check lat lon
        val forceLocation = if (locationAvailable) forceLoc else false
        val selectedLL = LatLng(lat, lon);

        // Check typeid
        val forceType = forceTypeid > 0L
        val selectedType = if (forceTypeid > 0L) forceTypeid else typeid

        if (locationAvailable && (selectedLL.latitude == 0.0 || selectedLL.longitude == 0.0)) {
            // Invalid lat/lon (both of them must exist)
            onDone.invoke(false, null, c.getString(R.string.err_qrscan_invalid_location))
            return
        }

        if (selectedType > 0L) {
            // retrieve system/domain and launch message creation if the given selectedType is valid
            DomainUtil.isMessageCategoryAvailable(c, lat, lon, selectedType, forceType) { category, failedToRetrieve ->
                if (category == null) {
                    // Typeid is not found in any domain queried by the location
                    onDone.invoke(false, null, c.getString(R.string.deeplink_err_type_not_found))
                } else {
                    // Category is valid. Launch message creation activity with the correct params
                    val param = BrowsableQueryParam().apply {
                        this.category = category
                        this.lat = selectedLL.latitude
                        this.lon = selectedLL.longitude
                        this.attributeValues = (param["attribute_values"] as HashMap<String, Any?>)
                        this.forceLocation = forceLocation
                        this.forceType = forceType
                    }
                    onDone.invoke(true, param, "")
                }
            }
        } else {
            // no category, no location? Just empty message creation
            val param = BrowsableQueryParam().apply {
                this.category = null
                this.lat = selectedLL.latitude
                this.lon = selectedLL.longitude
                this.forceLocation = forceLocation
                this.attributeValues = (param["attribute_values"] as HashMap<String, Any?>)
            }
            onDone.invoke(true, param, "")
        }
    }

}